apiVersion: v1
kind: Pod 
metadata:
  name: pythonpod-testdp6
  labels:
    env: python-testing6     
spec:
  containers:
    - name: pythonpod-testp6
      image: niraj1102/simplepython:latest
      imagePullPolicy: Always
      volumeMounts:
        - name: log-locp6
          mountPath: /c/Users/Niraj/log-locp6
      ports:
        - containerPort: 80
          name: pythonpod-testp6
  volumes:
    - name: log-locp6
      persistentVolumeClaim:
claimName: log-locp6
