apiVersion: v1
kind: Pod 
metadata:
  name: webpod-testp6
  labels:
    env: web-testing6     
spec:
  containers:
    - name: webpod-test6
      image: niraj1102/simplehtml:latest
      imagePullPolicy: Always
      volumeMounts:
        - name: log-loc6
          mountPath: /ws/log-loc
      ports:
        - containerPort: 80
          name: webpod-test6
  volumes:
    - name: log-loc6
      persistentVolumeClaim:
        claimName: log-loc6
