apiVersion: v1
kind: Service
metadata:
  name: pythonpod-testp6
  labels:
    env: python-testingp6
spec:
  selector:
    env: python-testingp6
  type: NodePort
  ports:
    - nodePort: 31003
      port: 80
      targetPort: 80
